import type { Metadata } from 'next'
import Link from 'next/link'
import LegalPageShell, { LegalSection } from '@/components/LegalPageShell'

export const metadata: Metadata = {
  title: 'Terms of Service | Scout',
  description: 'The terms that govern your use of Scout.',
}

export default function TermsPage() {
  return (
    <LegalPageShell title="Terms of Service" updated="July 13, 2026">
      <LegalSection title="Agreement">
        <p>
          These terms govern your use of Scout. By creating an account or using the
          service, you agree to them and to our{' '}
          <Link href="/privacy" className="underline hover:text-[--text-primary]">
            Privacy Policy
          </Link>
          . If you do not agree, please do not use Scout.
        </p>
        <p>
          Scout is an independent platform and is not affiliated with, endorsed by, or
          sponsored by Cornell University.
        </p>
      </LegalSection>

      <LegalSection title="Eligibility">
        <p>
          You must be at least 18 years old to use Scout. Student accounts additionally
          require a valid Cornell email address so we can verify you are a current
          Cornell student-athlete.
        </p>
      </LegalSection>

      <LegalSection title="Your account">
        <p>
          You agree to provide accurate information, keep your credentials secure, and
          use Scout only on your own behalf. You are responsible for activity that
          happens under your account.
        </p>
      </LegalSection>

      <LegalSection title="Acceptable use">
        <p>
          Scout exists for personal career networking between student-athletes and
          alumni. You agree not to:
        </p>
        <ul className="list-disc pl-5 space-y-1">
          <li>
            Scrape, bulk-export, resell, or redistribute the alumni directory or any data
            from it
          </li>
          <li>Spam, harass, or send unwanted commercial solicitation to anyone on Scout</li>
          <li>Misrepresent your identity, athletic history, or affiliation</li>
          <li>
            Use Scout for advertising, recruiting for other services, or any commercial
            purpose unrelated to your own career
          </li>
          <li>
            Probe, disable, or circumvent security features, or attempt to access data
            that isn&apos;t yours
          </li>
          <li>Use the service in violation of any applicable law</li>
        </ul>
      </LegalSection>

      <LegalSection title="Directory content">
        <p>
          Alumni starter profiles are compiled from publicly available sources and may be
          edited or removed by the alumni they describe. Directory data is provided for
          your individual networking use only — not for resale, aggregation, or any use
          outside Scout.
        </p>
      </LegalSection>

      <LegalSection title="AI-generated drafts">
        <p>
          Outreach drafts on Scout are generated by AI and are suggestions only. You are
          responsible for reviewing, editing, and deciding to send any message. Messages
          are sent from your own email account, not by Scout.
        </p>
      </LegalSection>

      <LegalSection title="Termination">
        <p>
          We may suspend or terminate accounts that violate these terms, harm other
          users, or abuse the service. You can delete your account at any time from
          Settings in the app.
        </p>
      </LegalSection>

      <LegalSection title="Disclaimer of warranties">
        <p>
          Scout is provided &ldquo;as is&rdquo; and &ldquo;as available,&rdquo; without
          warranties of any kind, express or implied. We do not guarantee the accuracy of
          directory profiles, the availability of the service, or any particular
          networking or career outcome.
        </p>
      </LegalSection>

      <LegalSection title="Limitation of liability">
        <p>
          To the maximum extent permitted by law, Scout and its team will not be liable
          for indirect, incidental, special, or consequential damages arising from your
          use of the service.
        </p>
      </LegalSection>

      <LegalSection title="Governing law">
        <p>
          These terms are governed by the laws of the State of New York, without regard
          to its conflict-of-laws rules.
        </p>
      </LegalSection>

      <LegalSection title="Changes and contact">
        <p>
          If we make material changes to these terms, we will update this page and the
          date at the top. Questions? Email{' '}
          <a
            href="mailto:contact@scoutcornell.com"
            className="underline hover:text-[--text-primary]"
          >
            contact@scoutcornell.com
          </a>
          .
        </p>
      </LegalSection>
    </LegalPageShell>
  )
}
