// ─────────────────────────────────────────────────────────────────────────────
// Scout Networking Agent — Mock Alumni Dataset
//
// 18 realistic Cornell athlete alumni across a range of industries,
// sports, and locations. Used for the local demo so no Supabase call
// is needed, and the demo runs fully offline.
// ─────────────────────────────────────────────────────────────────────────────

import type { AgentAlumni } from './types'

export const MOCK_ALUMNI: AgentAlumni[] = [
  // ── Sports / Marketing ───────────────────────────────────────────────────
  {
    id: 'a1',
    full_name: 'James Rivera',
    sport: 'Football',
    graduation_year: 2017,
    company: 'Octagon',
    role: 'Sports Marketing Manager',
    industry: 'Sports',
    location: 'New York, NY',
    linkedin_url: 'https://linkedin.com/in/james-rivera-cornell',
  },
  {
    id: 'a2',
    full_name: 'Jordan Mitchell',
    sport: 'Football',
    graduation_year: 2016,
    company: 'Adidas',
    role: 'Senior Brand Director',
    industry: 'Sports',
    location: 'Boston, MA',
    linkedin_url: 'https://linkedin.com/in/jordan-mitchell-adidas',
  },
  {
    id: 'a3',
    full_name: 'Marcus Thompson',
    sport: 'Football',
    graduation_year: 2019,
    company: 'ESPN',
    role: 'VP of Sports Marketing',
    industry: 'Media',
    location: 'New York, NY',
    linkedin_url: 'https://linkedin.com/in/marcus-thompson-espn',
  },
  {
    id: 'a4',
    full_name: 'David Kim',
    sport: 'Baseball',
    graduation_year: 2019,
    company: 'Red Bull',
    role: 'Marketing Director',
    industry: 'Sports',
    location: 'New York, NY',
    linkedin_url: 'https://linkedin.com/in/david-kim-redbull',
  },
  {
    id: 'a5',
    full_name: 'Chloe Davis',
    sport: 'Soccer',
    graduation_year: 2019,
    company: 'NBA',
    role: 'PR & Brand Manager',
    industry: 'Sports',
    location: 'New York, NY',
    linkedin_url: 'https://linkedin.com/in/chloe-davis-nba',
  },
  {
    id: 'a6',
    full_name: 'Sarah Chen',
    sport: 'Rowing',
    graduation_year: 2021,
    company: 'Nike',
    role: 'Brand Manager',
    industry: 'Sports',
    location: 'New York, NY',
    linkedin_url: 'https://linkedin.com/in/sarah-chen-nike',
  },
  {
    id: 'a7',
    full_name: 'Emma Walsh',
    sport: 'Lacrosse',
    graduation_year: 2020,
    company: 'CAA Sports',
    role: 'Sports Agent',
    industry: 'Sports',
    location: 'Los Angeles, CA',
    linkedin_url: 'https://linkedin.com/in/emma-walsh-caa',
  },
  {
    id: 'a8',
    full_name: 'Ryan Foster',
    sport: 'Football',
    graduation_year: 2015,
    company: 'Wasserman Media Group',
    role: 'Director of Brand Partnerships',
    industry: 'Sports',
    location: 'Boston, MA',
    linkedin_url: 'https://linkedin.com/in/ryan-foster-wasserman',
  },
  {
    id: 'a9',
    full_name: 'Aaliyah Brooks',
    sport: 'Track & Field',
    graduation_year: 2020,
    company: 'Bleacher Report',
    role: 'Content Marketing Manager',
    industry: 'Media',
    location: 'New York, NY',
    linkedin_url: 'https://linkedin.com/in/aaliyah-brooks-br',
  },
  // ── Finance ─────────────────────────────────────────────────────────────
  {
    id: 'a10',
    full_name: 'Alicia Brown',
    sport: 'Track & Field',
    graduation_year: 2020,
    company: 'Goldman Sachs',
    role: 'Investment Banking Analyst',
    industry: 'Finance',
    location: 'New York, NY',
    linkedin_url: 'https://linkedin.com/in/alicia-brown-gs',
  },
  {
    id: 'a11',
    full_name: 'Michael Torres',
    sport: 'Football',
    graduation_year: 2018,
    company: 'J.P. Morgan',
    role: 'Associate, Equity Research',
    industry: 'Finance',
    location: 'New York, NY',
    linkedin_url: 'https://linkedin.com/in/michael-torres-jpm',
  },
  // ── Consulting ───────────────────────────────────────────────────────────
  {
    id: 'a12',
    full_name: 'Priya Patel',
    sport: 'Swimming & Diving',
    graduation_year: 2021,
    company: 'Deloitte',
    role: 'Strategy Consultant',
    industry: 'Consulting',
    location: 'Boston, MA',
    linkedin_url: 'https://linkedin.com/in/priya-patel-deloitte',
  },
  {
    id: 'a13',
    full_name: 'Derek Huang',
    sport: 'Football',
    graduation_year: 2017,
    company: 'McKinsey & Company',
    role: 'Engagement Manager',
    industry: 'Consulting',
    location: 'Chicago, IL',
    linkedin_url: 'https://linkedin.com/in/derek-huang-mckinsey',
  },
  // ── Technology ───────────────────────────────────────────────────────────
  {
    id: 'a14',
    full_name: 'Tyler Park',
    sport: 'Football',
    graduation_year: 2018,
    company: 'Google',
    role: 'Product Manager, Ads',
    industry: 'Technology',
    location: 'San Francisco, CA',
    linkedin_url: 'https://linkedin.com/in/tyler-park-google',
  },
  {
    id: 'a15',
    full_name: 'Vanessa Osei',
    sport: 'Womens Basketball',
    graduation_year: 2022,
    company: 'Amazon',
    role: 'Software Engineer',
    industry: 'Technology',
    location: 'Seattle, WA',
    linkedin_url: 'https://linkedin.com/in/vanessa-osei-amazon',
  },
  // ── Healthcare / Other ───────────────────────────────────────────────────
  {
    id: 'a16',
    full_name: 'Liam O\'Brien',
    sport: 'Rugby',
    graduation_year: 2019,
    company: 'CVS Health',
    role: 'Operations Analyst',
    industry: 'Healthcare',
    location: 'Boston, MA',
    linkedin_url: 'https://linkedin.com/in/liam-obrien-cvs',
  },
  {
    id: 'a17',
    full_name: 'Gabrielle Martin',
    sport: 'Field Hockey',
    graduation_year: 2018,
    company: 'Endeavor',
    role: 'Event Marketing Manager',
    industry: 'Sports',
    location: 'New York, NY',
    linkedin_url: 'https://linkedin.com/in/gabrielle-martin-endeavor',
  },
  {
    id: 'a18',
    full_name: 'Chris Wallace',
    sport: 'Football',
    graduation_year: 2014,
    company: 'Turner Sports',
    role: 'Head of Digital Marketing',
    industry: 'Media',
    location: 'Atlanta, GA',
    linkedin_url: null,
  },
]
